#!/bin/bash
###########################################################
# Sets the NTP servers.
###########################################################
# Tested on:
#  - Raspbian
#  - CentOS 7
#  - OpenSuSE
###########################################################
TMP_FILE=/tmp/timesyncd.conf.tmp
CONF_FILE=/etc/systemd/timesyncd.conf
BAK_FILE=/etc/systemd/timesyncd.conf.bak
function cleanup() {
  if [ -e "$TMP_FILE" ]; then
    rm $TMP_FILE
  fi
}
function help() {
  echo "Sets the NTP servers."
  echo "Syntax: set_ntp [-h|s]"
  echo "options:"
  echo "h     Print this Help."
  echo "s     Pass one NTP server (many can be passed using the option more times)."
  echo
}
function write_ntp() {
  if [ $NTPSERVERS_LEN -gt 0 ] && [ $NTP_WRITTEN == 0 ]; then
    NTP_WRITTEN=1
    echo "NTP=${NTPSERVERS[0]}" >> $TMP_FILE
  fi
}
function write_fallback() {
  if [ $NTPSERVERS_LEN -gt 1 ] && [ $FALLBACK_WRITTEN == 0 ]; then
    FALLBACK_WRITTEN=1
    fallback=("${NTPSERVERS[@]:1}")  
    printf -v joined '%s ' "${fallback[@]}"
    echo "FallbackNTP=${joined}" >> $TMP_FILE
  fi
}
DOMAIN=''
NTPSERVERS=()
NOW=$(date '+%d/%m/%Y %H:%M:%S');
while getopts ":h:s:" option; do
  case $option in
    h) 
      help
      exit
      ;;
    s)
      NTPSERVERS[${#NTPSERVERS[@]}]=$OPTARG
      ;;
    \?) # Invalid option
      echo "Error: Invalid option"
      exit
      ;;
  esac
done
NTPSERVERS_LEN=${#NTPSERVERS[@]}
if [ "$NTPSERVERS_LEN" == "0" ]; then
  echo "Disabling systemd-timesyncd service."
  timedatectl set-ntp 0
  systemctl disable systemd-timesyncd.service
  systemctl stop systemd-timesyncd.service
  exit 0
fi
if [ -e "$TMP_FILE" ]; then
  rm $TMP_FILE
fi
trap cleanup SIGINT SIGTERM ERR EXIT
echo "# Generated by com.focussia.util.net." > $TMP_FILE
echo "# Date: $NOW" >> $TMP_FILE
NTP_WRITTEN=0
FALLBACK_WRITTEN=0
if [ -e "$CONF_FILE" ]; then
  while IFS= read -r line
  do
    APPEND=1
    if [[ "$line" == "# Generated"* ]] || [[ "$line" == "#Generated"* ]] || [[ "$line" == "# Date:"* ]]; then
      APPEND=0
    else
      if [[ "$line" == "NTP="* ]] || [[ "$line" == "FallbackNTP="* ]]; then
        APPEND=0
      fi
    fi
    if [ $APPEND == 1 ]; then
      echo "$line" >> $TMP_FILE
    fi
  done < "$CONF_FILE"
fi
write_ntp
write_fallback
if [ -e "$BAK_FILE" ]; then
  rm $BAK_FILE
fi
if [ -e "$CONF_FILE" ]; then
  mv $CONF_FILE $BAK_FILE
fi
mv $TMP_FILE $CONF_FILE
chmod 644 $CONF_FILE
chown root.root $CONF_FILE
systemctl enable systemd-timesyncd.service
systemctl restart systemd-timesyncd.service
timedatectl set-ntp 1
exit 0
